### PR TITLE
Fix amount filter

### LINKED ISSUE #16: Fieldset get not hydrated in form
My entity:

```php
/**
 * Class Company
 * @package App\Entity
 *
 * @Gedmo\Loggable(logEntryClass="App\Entity\CompanyLogEntry")
 * @Form\Hydrator("DoctrineModule\Stdlib\Hydrator\DoctrineObject")
 * @Form\Type("Account\Form\Company")
 * @Form\Name("company")
 * @ORM\Entity(repositoryClass="App\Repository\Company")
 * @ORM\Table(name="company")
 */
class Company implements CompanyInterface
{

   /**
     * @var Money
     * @Form\Type("money")
     * @Form\Options({"label":"Average value of shopping cart:"})
     * @Form\Name("averageValueOfShoppingCart")
     * @ ORM\Embedded(class = "Money\Money", columnPrefix = "average_value_of_shopping_cart_")
     */
    protected $averageValueOfShoppingCart;

    /**
     * {@inheritdoc}
     */
    public function getAverageValueOfShoppingCart()
    {
        return $this->averageValueOfShoppingCart;
    }

    /**
     * {@inheritdoc}
     */
    public function setAverageValueOfShoppingCart(Money $averageValueOfShoppingCart = null)
    {
        $this->averageValueOfShoppingCart = $averageValueOfShoppingCart;
    }

```
so when form filled and submitted then values stored in db as expected all right!  

here is my form (part)
```html
<div>
     <label for="averageValueOfShoppingCart">Average value of shopping cart:</label>
<div>
<div>
    <select name="averageValueOfShoppingCart[currency]">
    <option selected="selected" value="AED">United Arab Emirates Dirham</option>
    <option value="AFN">Afghan Afghani</option>
    <option value="ALL">Albanian Lek</option>
    <option value="AMD">Armenian Dram</option>
    <option value="ANG">Netherlands Antillean Guilder</option>
</select>
<input type="number" value="111" step="0.01" name="averageValueOfShoppingCart[amount]">            </div>
</div>
```
in db:

```
average_value_of_shopping_cart_amount 11100
average_value_of_shopping_cart_currency AED
```
so when load page now after then no values in form present I get dumped doctrine hydrator and see:

fieldNames for averageValueOfShoppingCart.amount and averageValueOfShoppingCart.currency for this props no method in entity exists and hydration will be skipped. 
I see that money module provides a Fieldset \ZFBrasil\DoctrineMoneyModule\Form\MoneyFieldset with injected his own hydrator 
```php
   $moneyFieldset = new MoneyFieldset();
   $moneyFieldset->setHydrator(new MoneyHydrator());
```
I suppose that this hydrator should fill form elements on $form->bind($companyEntity).
Should or shouldn't? pls tell my that is my mistake ;)

### PR DESCRIPTION
**Pull request by olekhy**
Fixes #16

### CODE REVIEW

File: test/Filter/AmountFilterTest.php [hunk 1]
```diff
@@ -15,6 +15,21 @@ public function testFiltersValueAsExpected()
...
+        $this->assertSame(0, $filter->filter(0));
+
+        $this->assertSame(0, $filter->filter('0'));
+    }
+
+    public function testShouldNotFilterEmpty()
+    {
+        $filter = new AmountFilter();
+
+        $this->assertSame(null, $filter->filter(''));
```
Comment (danizord) [inline test/Filter/AmountFilterTest.php]: `assertNull`

File: test/Filter/AmountFilterTest.php [hunk 2]
```diff
@@ -15,6 +15,21 @@ public function testFiltersValueAsExpected()
...
+
+        $this->assertSame(null, $filter->filter(null));
```
Comment (danizord) [inline test/Filter/AmountFilterTest.php]: `assertNull`

**Comment by danizord** [comment]
@olekhy thanks!
